import 'package:get/get.dart';
import '../../model/critical_question.dart';

class CriticalQuestionsController extends GetxController {
  final completed = 12.obs;
  final total = 60.obs;

  final RxList<CriticalQuestion> questions = <CriticalQuestion>[
    CriticalQuestion(id: 1, text: "Hành vi nào bị nghiêm cấm khi lái xe ô tô, mô tô?", status: "ĐÃ THUỘC", tag: "Khái niệm & Quy tắc", icon: "warning"),
    CriticalQuestion(id: 2, text: "Người điều khiển phương tiện giao thông đường bộ phải tuân thủ quy tắc giao thông nào sau đây?", status: "ĐÃ THUỘC", tag: "Khái niệm & Quy tắc", icon: "warning"),
    CriticalQuestion(id: 3, text: "Hành vi điều khiển xe cơ giới chạy quá tốc độ quy định bị xử lý như thế nào?", status: "ĐÃ THUỘC", tag: "Tốc độ & Vượt ẩu", icon: "speed"),
    CriticalQuestion(id: 4, text: "Người lái xe sử dụng rượu bia bị phạt bao nhiêu tiền?", status: "ĐÃ THUỘC", tag: "Nồng độ cồn", icon: "local_bar"),
    CriticalQuestion(id: 5, text: "Với xe mô tô, khi nồng độ cồn vượt mức quy định, mức xử phạt cao nhất là bao nhiêu?", status: "ĐÃ THUỘC", tag: "Nồng độ cồn", icon: "local_bar"),
    CriticalQuestion(id: 6, text: "Hành vi nào sau đây bị nghiêm cấm đối với người điều khiển xe cơ giới?", status: "ĐÃ THUỘC", tag: "Cực kỳ nghiêm trọng", icon: "warning"),
    CriticalQuestion(id: 7, text: "Người lái xe khi gặp hiệu lệnh của người điều khiển giao thông phải chấp hành thế nào?", status: "ĐÃ THUỘC", tag: "Khái niệm & Quy tắc", icon: "warning"),
    CriticalQuestion(id: 8, text: "Khi điều khiển xe cơ giới, người lái xe được phép sử dụng điện thoại di động không?", status: "ĐÃ THUỘC", tag: "Cực kỳ nghiêm trọng", icon: "warning"),
    CriticalQuestion(id: 9, text: "Khi có tín hiệu đèn đỏ, người điều khiển phương tiện phải dừng lại trước vạch dừng xe. Đúng hay sai?", status: "CHƯA LÀM", tag: "Khái niệm & Quy tắc", icon: "warning"),
    CriticalQuestion(id: 10, text: "Người lái xe mô tô có được phép đi vào đường cao tốc không?", status: "ĐÃ THUỘC", tag: "Khái niệm & Quy tắc", icon: "warning"),
    CriticalQuestion(id: 11, text: "Người đi bộ có được phép đi vào phần đường dành cho xe cơ giới không?", status: "CHƯA LÀM", tag: "Khái niệm & Quy tắc", icon: "warning"),
    CriticalQuestion(id: 12, text: "Người lái xe phải giảm tốc độ trong trường hợp nào sau đây?", status: "ĐÃ THUỘC", tag: "Tốc độ & Vượt ẩu", icon: "speed"),
    CriticalQuestion(id: 13, text: "Khi vượt xe, người lái xe phải thực hiện như thế nào?", status: "CHƯA LÀM", tag: "Tốc độ & Vượt ẩu", icon: "speed"),
    CriticalQuestion(id: 14, text: "Trường hợp nào sau đây xe không được phép vượt?", status: "CHƯA LÀM", tag: "Tốc độ & Vượt ẩu", icon: "speed"),
    CriticalQuestion(id: 15, text: "Xe ô tô tải có được phép chở người trên thùng xe không?", status: "ĐÃ THUỘC", tag: "Cực kỳ nghiêm trọng", icon: "warning"),
    CriticalQuestion(id: 16, text: "Người lái xe có được phép bấm còi liên tục trong khu dân cư không?", status: "CHƯA LÀM", tag: "Khái niệm & Quy tắc", icon: "warning"),
    CriticalQuestion(id: 17, text: "Hành vi đưa xe cơ giới không bảo đảm tiêu chuẩn an toàn kỹ thuật vào tham gia giao thông bị xử phạt thế nào?", status: "CHƯA LÀM", tag: "Cực kỳ nghiêm trọng", icon: "warning"),
    CriticalQuestion(id: 18, text: "Người điều khiển xe mô tô hai bánh, xe gắn máy không được thực hiện hành vi nào?", status: "CHƯA LÀM", tag: "Cực kỳ nghiêm trọng", icon: "warning"),
    CriticalQuestion(id: 19, text: "Người điều khiển xe cơ giới phải bật tín hiệu xin đường và từ từ chuyển hướng khi nào?", status: "CHƯA LÀM", tag: "Khái niệm & Quy tắc", icon: "warning"),
    CriticalQuestion(id: 20, text: "Khi lái xe trong đường hầm, người lái xe phải thực hiện những quy định nào?", status: "CHƯA LÀM", tag: "Khái niệm & Quy tắc", icon: "warning"),
    CriticalQuestion(id: 21, text: "Sử dụng rượu, bia khi lái xe, nếu bị phát hiện thì bị xử lý như thế nào?", status: "ĐÃ THUỘC", tag: "Nồng độ cồn", icon: "local_bar"),
    CriticalQuestion(id: 22, text: "Người lái xe phải có nghĩa vụ gì khi xảy ra tai nạn giao thông?", status: "CHƯA LÀM", tag: "Cực kỳ nghiêm trọng", icon: "warning"),
    CriticalQuestion(id: 23, text: "Người lái xe phải nhường đường cho xe đi ngược chiều trong trường hợp nào?", status: "CHƯA LÀM", tag: "Khái niệm & Quy tắc", icon: "warning"),
    CriticalQuestion(id: 24, text: "Tại nơi giao nhau không có báo hiệu đi theo vòng xuyến, người lái xe phải nhường đường cho xe nào?", status: "CHƯA LÀM", tag: "Khái niệm & Quy tắc", icon: "warning"),
    CriticalQuestion(id: 25, text: "Hành vi điều khiển xe cơ giới chạy quá tốc độ quy định, giành đường, vượt ẩu có bị nghiêm cấm không?", status: "CHƯA LÀM", tag: "Tốc độ & Vượt ẩu", icon: "speed"),
    CriticalQuestion(id: 26, text: "Người điều khiển xe cơ giới phải giữ khoảng cách an toàn với xe phía trước như thế nào?", status: "CHƯA LÀM", tag: "Tốc độ & Vượt ẩu", icon: "speed"),
    CriticalQuestion(id: 27, text: "Tốc độ tối đa cho phép đối với xe ô tô trên đường cao tốc là bao nhiêu?", status: "CHƯA LÀM", tag: "Tốc độ & Vượt ẩu", icon: "speed"),
    CriticalQuestion(id: 28, text: "Khi xe ô tô bị hỏng giữa đường, người lái xe phải xử lý như thế nào?", status: "CHƯA LÀM", tag: "Cực kỳ nghiêm trọng", icon: "warning"),
    CriticalQuestion(id: 29, text: "Khi điều khiển xe ô tô, người lái xe phải thắt dây an toàn và yêu cầu hành khách phải thắt dây an toàn?", status: "CHƯA LÀM", tag: "Cực kỳ nghiêm trọng", icon: "warning"),
    CriticalQuestion(id: 30, text: "Người lái xe không được phép quay đầu xe ở khu vực nào?", status: "CHƯA LÀM", tag: "Khái niệm & Quy tắc", icon: "warning"),
    CriticalQuestion(id: 31, text: "Khi có tín hiệu của xe ưu tiên, người lái xe phải xử lý thế nào?", status: "CHƯA LÀM", tag: "Khái niệm & Quy tắc", icon: "warning"),
    CriticalQuestion(id: 32, text: "Tại nơi đường bộ giao nhau cùng mức với đường sắt, người điều khiển phương tiện phải xử lý thế nào?", status: "CHƯA LÀM", tag: "Giao cắt đường sắt", icon: "train"),
    CriticalQuestion(id: 33, text: "Khi qua đường sắt không có rào chắn, người lái xe phải xử lý thế nào?", status: "CHƯA LÀM", tag: "Giao cắt đường sắt", icon: "train"),
    CriticalQuestion(id: 34, text: "Người điều khiển xe cơ giới có được phép dừng xe, đỗ xe trên đường sắt không?", status: "CHƯA LÀM", tag: "Giao cắt đường sắt", icon: "train"),
    CriticalQuestion(id: 35, text: "Khi gặp biển báo cấm đi ngược chiều, người lái xe phải xử lý thế nào?", status: "CHƯA LÀM", tag: "Khái niệm & Quy tắc", icon: "warning"),
    CriticalQuestion(id: 36, text: "Người ngồi trên xe mô tô hai bánh, xe gắn máy phải đội mũ bảo hiểm đúng quy cách?", status: "CHƯA LÀM", tag: "Cực kỳ nghiêm trọng", icon: "warning"),
    CriticalQuestion(id: 37, text: "Người lái xe mô tô hai bánh có được phép sử dụng ô (dù) khi tham gia giao thông?", status: "CHƯA LÀM", tag: "Cực kỳ nghiêm trọng", icon: "warning"),
    CriticalQuestion(id: 38, text: "Độ tuổi tối thiểu để được cấp giấy phép lái xe hạng B1 là bao nhiêu?", status: "CHƯA LÀM", tag: "Khái niệm & Quy tắc", icon: "warning"),
    CriticalQuestion(id: 39, text: "Giấy phép lái xe bị thu hồi trong trường hợp nào?", status: "CHƯA LÀM", tag: "Cực kỳ nghiêm trọng", icon: "warning"),
    CriticalQuestion(id: 40, text: "Xe cơ giới, xe máy chuyên dùng bắt buộc phải đăng ký và gắn biển số khi tham gia giao thông?", status: "CHƯA LÀM", tag: "Khái niệm & Quy tắc", icon: "warning"),
    CriticalQuestion(id: 41, text: "Khi điều khiển xe trên đường cao tốc, người lái xe có được phép dừng xe trên phần đường xe chạy?", status: "CHƯA LÀM", tag: "Tốc độ & Vượt ẩu", icon: "speed"),
    CriticalQuestion(id: 42, text: "Tốc độ tối đa của xe ô tô chạy trong khu vực đông dân cư khi có dải phân cách giữa là bao nhiêu?", status: "CHƯA LÀM", tag: "Tốc độ & Vượt ẩu", icon: "speed"),
    CriticalQuestion(id: 43, text: "Khi đi qua trường học, bệnh viện, người lái xe phải xử lý thế nào?", status: "CHƯA LÀM", tag: "Khái niệm & Quy tắc", icon: "warning"),
    CriticalQuestion(id: 44, text: "Người điều khiển xe cơ giới có được phép lùi xe ở đường một chiều không?", status: "CHƯA LÀM", tag: "Khái niệm & Quy tắc", icon: "warning"),
    CriticalQuestion(id: 45, text: "Khi gặp xe buýt đang dừng đón, trả khách, người lái xe phải xử lý thế nào?", status: "CHƯA LÀM", tag: "Khái niệm & Quy tắc", icon: "warning"),
    CriticalQuestion(id: 46, text: "Người lái xe phải nhường đường cho người đi bộ ở khu vực nào?", status: "CHƯA LÀM", tag: "Khái niệm & Quy tắc", icon: "warning"),
    CriticalQuestion(id: 47, text: "Xe cơ giới đang đi trên đường gặp trời mưa to, đường trơn phải xử lý thế nào?", status: "CHƯA LÀM", tag: "Tốc độ & Vượt ẩu", icon: "speed"),
    CriticalQuestion(id: 48, text: "Khi đổ đèo, xuống dốc dài, người lái xe phải xử lý thế nào?", status: "CHƯA LÀM", tag: "Tốc độ & Vượt ẩu", icon: "speed"),
    CriticalQuestion(id: 49, text: "Người lái xe có được phép điều khiển xe khi giấy phép lái xe đã hết hạn không?", status: "CHƯA LÀM", tag: "Cực kỳ nghiêm trọng", icon: "warning"),
    CriticalQuestion(id: 50, text: "Người điều khiển xe cơ giới có được phép chở hàng vượt quá trọng tải thiết kế không?", status: "CHƯA LÀM", tag: "Cực kỳ nghiêm trọng", icon: "warning"),
    CriticalQuestion(id: 51, text: "Người lái xe mô tô có được phép chở 3 người trên xe không?", status: "CHƯA LÀM", tag: "Cực kỳ nghiêm trọng", icon: "warning"),
    CriticalQuestion(id: 52, text: "Hành vi bỏ trốn sau khi gây tai nạn giao thông bị xử lý thế nào?", status: "CHƯA LÀM", tag: "Cực kỳ nghiêm trọng", icon: "warning"),
    CriticalQuestion(id: 53, text: "Nồng độ cồn cho phép đối với người lái xe ô tô là bao nhiêu?", status: "CHƯA LÀM", tag: "Nồng độ cồn", icon: "local_bar"),
    CriticalQuestion(id: 54, text: "Khi gặp đoàn xe quân sự, người lái xe phải xử lý thế nào?", status: "CHƯA LÀM", tag: "Khái niệm & Quy tắc", icon: "warning"),
    CriticalQuestion(id: 55, text: "Hành vi đi ngược chiều trên đường cao tốc bị xử phạt thế nào?", status: "CHƯA LÀM", tag: "Tốc độ & Vượt ẩu", icon: "speed"),
    CriticalQuestion(id: 56, text: "Khi gặp chướng ngại vật phía trước, người lái xe phải thực hiện thao tác gì?", status: "CHƯA LÀM", tag: "Khái niệm & Quy tắc", icon: "warning"),
    CriticalQuestion(id: 57, text: "Người điều khiển xe ô tô không được phép tránh xe, vượt xe tại vị trí nào?", status: "CHƯA LÀM", tag: "Tốc độ & Vượt ẩu", icon: "speed"),
    CriticalQuestion(id: 58, text: "Thứ tự ưu tiên các loại xe khi gặp nhau tại nơi giao nhau là gì?", status: "CHƯA LÀM", tag: "Khái niệm & Quy tắc", icon: "warning"),
    CriticalQuestion(id: 59, text: "Người lái xe có được sử dụng chất ma túy khi điều khiển phương tiện giao thông không?", status: "CHƯA LÀM", tag: "Cực kỳ nghiêm trọng", icon: "warning"),
    CriticalQuestion(id: 60, text: "Người lái xe phải làm gì khi thấy có trẻ em hoặc học sinh đi bộ trên đường?", status: "CHƯA LÀM", tag: "Khái niệm & Quy tắc", icon: "warning"),
  ].obs;

  void goBack() => Get.back();
  void openQuestion(int id) {}
}
